version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: password
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on: 
      - db
      - redis
    environment: 
    - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  redis:
    image: redis:6.2.5
  sidekiq:
    build: .
    volumes:
      - .:/app
    entrypoint: /usr/bin/sidekiq-entrypoint.sh
    environment: 
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    depends_on: 
      - app
      - db